### ISSUE TITLE
Moving Mail From Shared Mailbox

### ISSUE THREAD

**Issue by ghost** [AmaliaKalio/Nephthis-BP-VBO---Internal-MAPI-v2#1]
Thanks for creating this. Are you able to successfully move mail from folders in a shared mailbox? I can move mail fine from my own inbox but when using a shared mailbox moving an item from inbox to "Inbox\Subfolder" I get an error. The specific line seems to be "folder = folder.Folders(name)" that's causing the "An object could not be found." error.

**Comment by AmaliaKalio** [comment]
Try just listing the subfolder without the preceding "Inbox\\". I just tested it on my own machine and it was happy.

![image](https://user-images.githubusercontent.com/9390932/117363234-ec18e200-ae81-11eb-8807-4fb7b4869211.png)

**Comment by ghost** [comment]
Weird - still no go for me no matter how I list the subfolder name. Tried a few different shared mailboxes and email items. 
![image](https://user-images.githubusercontent.com/45922513/117363838-22a72a80-ae8b-11eb-97e1-f57f5fa077c9.png)

**Comment by AmaliaKalio** [comment]
I've previously seen some cases where the folder needs to be marked as visible in the properties window. It seems to be hit or miss as to when this is required (I'm guessing something to do with Exchange/O365 server settings).
![image](https://user-images.githubusercontent.com/9390932/117364377-744bb700-ae83-11eb-8213-3733d4d52004.png)

**Comment by ghost** [comment]
So it looks like I'm not getting any folders returned when setting up the shared folder. If I run this code it returns nothing but if I run that while keeping the subfolder input var blank it returns all of my personal subfolders.

for each folder in folder.Folders
  New_Entry_ID = New_Entry_ID + folder.Name
next

**Comment by AmaliaKalio** [comment]
Ack. If setting the visibility didn't change it, I know that there was a backend security change to Exchange that broke some of this functionality.

Going back to your screenshot, I noticed that it was based on an outdated copy of the XML. I don't _think_ there's a huge difference, but to be safe I've updated the Git release with my latest fork as there's a potential that the code was before I incorporated the latest OOB updates to address this. See if that fixes it for you.

**Comment by ghost** [comment]
Awesome - I'll try that out. Thank you!

**Comment by ghost** [comment]
I got it to work. I had to uncheck use cached exchange mode in my account settings and restart outlook. After that I could pull shared folders. Thanks for the help!

**Comment by AmaliaKalio** [comment]
Awesome! Glad it works!

**Comment by AmaliaKalio** [comment]
Closing with resolution of turning off cached exchange mode.
